import logging
import warnings
from abc import ABC, abstractmethod
from collections.abc import Callable
from typing import Any

import numpy as np
import pandas as pd
import torch
from pgmpy import config
from pgmpy.factors.discrete import TabularCPD
from pgmpy.models import BayesianNetwork
from pgmpy.sampling import BayesianModelSampling
from pydantic import BaseModel
from rich.progress import Progress

from pgms.generators.base.utils import bernoulli_ucb, tensor_normalize

# Set up logging
logging.basicConfig()
logger = logging.getLogger(__name__)
logger.setLevel(logging.INFO)
# Warnings occur even when off by a floating point error (~1e-16)
logging.getLogger("pgmpy").setLevel(logging.ERROR)
warnings.filterwarnings(
    "ignore",
    message="Passing a DataFrame to DataFrame.from_records is deprecated.*",
    category=FutureWarning,
)

config.set_backend("torch")
config.set_dtype(torch.float32)

### REJECTION SAMPLING CONSTANTS
# Throw error if the rejection sampling success rate is below this value
REJ_SAMP_FAIL_PROB = 0.01
# Throw error if the rejection sampling success rate is below this value for large sample sizes
REJ_SAMP_LARGE_FAIL_PROB = 0.05
REJ_SAMP_LARGE_FAIL_SIZE = 1000000
# Warn if the rejection sampling success rate is below this value
REJ_SAMP_WARN_PROB = 0.05
# Rejection sampling dynamically adjusts based on the failure rate and these parameters
REJ_SAMP_MIN_MULTIPLIER = 0.05
REJ_SAMP_OVERSAMPLE = 1.5


class Edge(BaseModel):
    start: str
    end: str

    def __getitem__(self, index):
        return [self.start, self.end][index]


class PGMGenerator(ABC):
    """
    Base class for Probabilistic Graphical Model (PGM) generators.
    This class wraps the BayesianNetwork capabilities of pgmpy,
    extending them to enable multiple cascaded PGMs with arbitrary
    post-processing steps between them.
    Subclasses should implement the following methods:
        - get_data
        - get_edges
        - get_variables
        - get_cpds
    """

    def __init__(self, *args, **kwargs):
        """Subclasses should override this instead of __init__"""
        data = self.get_data(*args, **kwargs)
        edges = self.get_edges(*args, **kwargs)
        self.variables = self.get_variables(data)
        self.mappings = self.get_mappings(data)
        cpds = self.get_cpds(data)
        self.postprocessing_steps = self.get_postprocessing_steps()
        self.latents = self.get_latents()
        self.models = self._build_network(edges, cpds)
        # Root nodes are nodes in the top-level model with no parents
        self.root_nodes = [
            node for node, degree in self.models[0].in_degree() if degree == 0
        ]

    @abstractmethod
    def get_data(self, *args, **kwargs) -> BaseModel:
        """Load statistical data for the PGM."""
        ...

    @abstractmethod
    def get_edges(self, *args, **kwargs) -> list[list[Edge]]:
        """Load edges for the PGM."""
        ...

    @abstractmethod
    def get_variables(self, data: BaseModel) -> dict[str, list[str]]:
        """Load variables for the PGM."""
        ...

    @abstractmethod
    def get_cpds(self, data: BaseModel) -> list[dict[str, TabularCPD]]:
        """Create Conditional Probability Distributions (edges in the PGM)."""
        ...

    def get_postprocessing_steps(self) -> list[list[Callable]] | None:
        """Load postprocessing steps for the PGM."""
        return None

    def get_latents(self) -> list[str]:
        """Load latent variables for the PGM."""
        return []

    def get_mappings(self, data: BaseModel) -> dict[str, pd.DataFrame]:
        """Load deterministic mappings for use in postprocessing."""
        return {}

    def _build_network(
        self,
        model_edges: list[list[Edge]],
        cpds: list[dict[str, TabularCPD]],
    ) -> list[BayesianNetwork]:
        """
        Create Bayesian Models based on model_edges, adding root nodes as needed.
        Add CPDs to the models.
        """
        logger.info("Successfully added and verified all CPDs.")
        models = [BayesianNetwork(edges) for edges in model_edges]
        # Add nodes with defined cpds to model (if not already present)
        for model, model_cpds in zip(models, cpds):
            for node in model_cpds.keys():
                if node not in model.nodes():
                    model.add_node(node)
        # Assign all nodes without CPDs to flat priors (assumed to be generated by a previous model)
        for model, model_cpds in zip(models, cpds):
            for node in model.nodes:
                if node in model_cpds:
                    continue
                values = tensor_normalize(
                    torch.tensor([[1.0] * len(self.variables[node])]).T,
                    config.get_dtype(),
                    config.get_device(),
                )
                model_cpds[node] = TabularCPD(
                    variable=node,
                    variable_card=len(self.variables[node]),
                    values=values,
                    state_names={node: list(self.variables[node])},
                )
            for name, cpd in model_cpds.items():
                model.add_cpds(cpd)
        logger.info("Successfully built the network.")
        return models

    def fill_na_and_gen_cpd(
        self,
        counts: pd.DataFrame,
        variable_name: str,
        evidence: list,
        pseudocount: float = 1e-10,
    ) -> TabularCPD:
        """
        Fill missing combinations in a count table with zeros, add a pseudocount,
        and generate a Tabular CPD.

        Args:
            counts: DataFrame containing the original counts
            variable_name: Name of this variable
            evidence: List of evidence variable names defining the full contingency table
            pseudocount: Small value to add to avoid zero probabilities (default: 1e-10)

        Returns:
            TabularCPD with:
            - All possible combinations represented (implicitly zero for missing combinations)
            - Pseudocount added during dense array conversion
        """
        columns = evidence + [variable_name]
        counts = counts[columns + ["count"]]

        # Get the dimensions for each variable
        dims = [len(self.variables[k]) for k in columns]

        # Convert data points to row and column indices for 2D sparse matrix
        var_dim = dims[-1]  # dimension of the variable
        evidence_dims = dims[:-1]  # dimensions of evidence variables
        evidence_size = np.prod(evidence_dims) if evidence_dims else 1

        def _build_rows():
            # Calculate row (variable) indices
            try:
                counts_var = counts[variable_name].cat.codes.to_numpy(dtype=np.int64)
            except AttributeError as e:
                print(f"{variable_name}, {counts.columns}")
                raise e
            return torch.from_numpy(counts_var)

        def _build_cols():
            # Initialize column indices
            cols = torch.zeros(len(counts), dtype=torch.long)
            if not evidence:
                return cols
            # Calculate strides for each evidence variable
            strides = [
                torch.prod(torch.tensor(evidence_dims[i + 1 :], dtype=torch.long))
                for i in range(len(evidence))
            ]

            # Vectorized calculation for each evidence variable
            for ev, stride in zip(evidence, strides):
                try:
                    counts_ev = counts[ev].cat.codes.to_numpy(dtype=np.int64)
                except AttributeError as e:
                    print(f"{ev}, {counts.columns}")
                    raise e
                ev_indices = torch.from_numpy(counts_ev)
                cols += ev_indices * stride
            return cols

        rows = _build_rows()
        cols = _build_cols()
        values = torch.tensor(counts["count"].values, dtype=config.get_dtype())

        # Create sparse tensor
        sparse_counts = torch.sparse_coo_tensor(
            indices=torch.stack([rows, cols]),
            values=values,
            size=(var_dim, evidence_size),
            device=config.get_device(),
        )

        # Convert to dense array and add pseudocount
        dense_counts = tensor_normalize(
            sparse_counts.to_dense() + pseudocount,
            config.get_dtype(),
            config.get_device(),
        )

        return TabularCPD(
            variable=variable_name,
            variable_card=len(self.variables[variable_name]),
            values=dense_counts,
            evidence=evidence,
            evidence_card=[len(self.variables[k]) for k in evidence],
            state_names={
                k: list(self.variables[k]) for k in evidence + [variable_name]
            },
        )

    def _validate_evidence(self, evidence: dict[str, Any | list[Any]]) -> None:
        """
        Validate that the evidence provided is consistent
        with the variables in the PGM.
        """
        class_name = self.__class__.__name__
        for var, state in evidence.items():
            if var not in self.variables:
                raise ValueError(f"Variable {var} not found in {class_name}.")
            state_vars = state if isinstance(state, list) else [state]
            for s in state_vars:
                if s not in self.variables[var]:
                    raise ValueError(
                        f"{s} is not an allowed value for {var} in {class_name}."
                    )

    def generate_samples(
        self,
        size: int = 1,
        evidence: dict[str, Any | list[Any]] | None = None,
        seed: int | None = None,
        partial_samples: pd.DataFrame | None = None,
        disable_progress_bar: bool = False,
    ) -> pd.DataFrame:
        """Generate samples from the PGM."""
        if seed is not None:
            np.random.seed(seed)
        evidence = {} if evidence is None else evidence.copy()
        self._validate_evidence(evidence)
        # More efficient to set root node evidence as partial samples directly
        for var, state in list(evidence.items()):
            if var in self.root_nodes and not isinstance(state, list):
                if partial_samples is None:
                    partial_samples = pd.DataFrame({var: [state] * size})
                else:
                    partial_samples[var] = state
                del evidence[var]
        # Show progress by default only if rejection sampling
        show_progress = True if evidence else False
        if disable_progress_bar:
            show_progress = False
        samples = self._rejection_sample(
            evidence=evidence,
            size=size,
            show_progress=show_progress,
            partial_samples=partial_samples,
        )
        samples = samples.drop(columns=self.latents)
        samples = samples.replace({float("nan"): None})
        return samples

    def _rejection_sample(
        self,
        evidence: dict[str, Any | list[Any]],
        size: int,
        show_progress: bool,
        partial_samples: pd.DataFrame | None,
    ) -> pd.DataFrame:
        """
        This method follows pgmpy.BayesianModelSampling.rejection_sample, but with the
        ability to rejection sample across multiple cascaded models. It also
        fixes the bug where partial_samples are ignored when no evidence is provided.
        """

        # Setup array to be returned
        sampled = pd.DataFrame()
        prob = 1
        i = 0

        # Do the sampling by generating samples from forward sampling and rejecting the
        # samples which do not match our evidence. Keep doing until we have enough
        # samples.
        progress = None
        task_id = None
        if show_progress and config.SHOW_PROGRESS:
            progress = Progress()
            task_id = progress.add_task("Sampling", total=size)
            progress.start()

        slow_progress_warning = False

        while i < size:
            # Dynamically changes based on the strictness of the evidence
            if evidence:
                _size = int(
                    ((size - i) / max(prob, REJ_SAMP_MIN_MULTIPLIER))
                    * REJ_SAMP_OVERSAMPLE
                )
            else:
                _size = size

            # If partial_samples is specified, can only generate < partial_samples.shape[0] number of samples
            # at a time. For simplicity, just generate the same size as partial_samples.shape[0].
            if partial_samples is not None:
                _size = partial_samples.shape[0]

            _sampled = self._forward_sample(size=_size, partial_samples=partial_samples)

            for var, state in evidence.items():
                if isinstance(state, list):
                    _sampled = _sampled[_sampled[var].isin(state)]
                else:
                    _sampled = _sampled[_sampled[var] == state]

            prob = len(_sampled) / _size
            sampled = pd.concat([sampled, _sampled], axis=0, join="outer").iloc[
                :size, :
            ]
            i += _sampled.shape[0]

            prob_ucb = bernoulli_ucb(len(_sampled), _size)
            if prob_ucb < REJ_SAMP_FAIL_PROB or (
                prob_ucb < REJ_SAMP_LARGE_FAIL_PROB and _size > REJ_SAMP_LARGE_FAIL_SIZE
            ):
                if progress is not None:
                    progress.stop()
                raise TimeoutError(
                    f"The given requirements {evidence} are too restrictive. Please remove some restrictions and try again."
                )
            elif prob_ucb < REJ_SAMP_WARN_PROB and not slow_progress_warning:
                logger.warning(
                    f"Rejection sampling on the given evidence has a <{prob_ucb:.0%} success rate. This may result in slow progress."
                )
                slow_progress_warning = True

            if progress is not None:
                # Update at maximum to `size`
                comp = _sampled.shape[0] if i < size else size - (i - _sampled.shape[0])
                progress.update(task_id, advance=comp)

        if progress is not None:
            progress.stop()

        sampled = sampled.reset_index(drop=True)
        return sampled

    def _forward_sample(
        self, size: int, partial_samples: pd.DataFrame | None
    ) -> pd.DataFrame:
        samples = partial_samples
        postprocessing_steps = self.postprocessing_steps
        if postprocessing_steps is None:
            postprocessing_steps = [None] * len(self.models)
        for model, model_postprocessing_steps in zip(self.models, postprocessing_steps):
            inference = BayesianModelSampling(model)

            # Map partial samples to internal model state names
            model_partial_samples = None
            if samples is not None:
                model_partial_samples = samples.copy()
                for column in model_partial_samples.columns:
                    try:
                        mapping = inference.state_names_map[column]
                    except KeyError:
                        continue
                    reverse_mapping = {v: k for k, v in mapping.items()}
                    model_partial_samples[column] = model_partial_samples[column].map(
                        reverse_mapping
                    )

            new_samples = inference.forward_sample(
                size=size, partial_samples=model_partial_samples, show_progress=False
            )
            if samples is None:
                samples = new_samples
            else:
                common_columns = set(samples.columns) & set(new_samples.columns)
                samples = pd.concat(
                    [samples, new_samples.drop(columns=common_columns)], axis=1
                )

            if model_postprocessing_steps:
                for model_postprocessing_step in model_postprocessing_steps:
                    samples = model_postprocessing_step(samples)

        return samples
